$ErrorActionPreference = 'Stop'
$path = "$PSScriptRoot\..\translations\packages\01_hints_tutorials.csv"
$translations = @{
    'hint_alchemy' = 'Смеси'
    'hint_build' = 'Построй'
    'hint_climb' = 'Изкачи се'
    'hint_craft' = 'Изработи'
    'hint_cremate_body' = 'Кремирай'
    'hint_draw_water' = 'Загреби вода'
    'hint_drop_body' = 'Пусни тялото'
    'hint_exit' = 'Излез'
    'hint_fertilize' = 'Тори'
    'hint_grave' = 'Гроб'
    'hint_interaction' = 'Взаимодействай'
    'hint_open' = 'Отвори'
    'hint_pick_up' = 'Вдигни'
    'hint_place_body' = 'Постави тялото'
    'hint_plant' = 'Засади'
    'hint_pray' = 'Моли се'
    'hint_put' = 'Постави'
    'hint_put_flag' = 'Постави знамето'
    'hint_put_zombie' = 'Постави зомбито'
    'hint_required_mastery' = 'Необходимо майсторство'
    'hint_reset' = 'Нулирай'
    'hint_set_to_hot_bar' = 'Задай в бързия панел'
    'hint_sleep' = 'Спи'
    'hint_speak' = 'Говори'
    'hint_steam_up' = 'Подвий ръкави'
    'hint_survey' = 'Проучи'
    'hint_survey_noun' = 'Проучване'
    'hint_take' = 'Вземи'
    'hint_take_all' = 'Вземи всички'
    'hint_take_flag' = 'Вземи знамето'
    'hint_take_water' = 'Вземи вода'
    'hint_teleport' = 'Телепортирай се'
    'hint_try_to_remove' = 'Опитай се да я премахнеш'
    'hint_work' = 'Работи'
    'hint_insp_reward' = 'Запълва лентата за вдъхновение и ти дава %1 точки.'
    'hint_science_decompose' = 'Може да се разгради на Масата за проучване, за да получиш'
    'hint_use_clothes' = 'Използвай, за да добавиш към колекцията си от дрехи.'
    'hint_use_read' = 'Използвай, за да прочетеш.'
    'hint_use_seeds' = 'Използвай, за да започнеш засаждането.'
    'tut_alchemy_hdr' = 'Урок: Алхимия'
    'tut_battle_1_hdr' = 'Урок: Подготовка за битка'
    'tut_battle_2_hdr' = 'Урок: Битка'
    'tut_commerce_hdr' = 'Урок: Търговия'
    'tut_craft_hdr' = 'Урок: Изработка'
    'tut_energy_hdr' = 'Урок: Енергия'
    'tut_factory_hdr' = 'Урок: Фабрика'
    'tut_farming_hdr' = 'Урок: Земеделие'
    'tut_fishing_hdr' = 'Урок: Риболов'
    'tut_grave_hdr' = 'Урок: Гробището'
    'tut_insanity_hdr' = 'Урок: Лудост'
    'tut_insp_talents_hdr' = 'Урок: Вдъхновения и таланти'
    'tut_modules_hdr' = 'Урок: Модули на гробището'
    'tut_pr_machine_hdr' = 'Урок: Машина за намаляване на паниката'
    'tut_resurrection_hdr' = 'Урок: Възкресение'
    'tut_alchemy_craft' = 'За изработката на алхимични рецепти е нужна <sprite name="alchemy_flask">. Трябва да ги заредиш на рафта за колби.'
    'tut_alchemy_folio' = 'Всички открити от теб формули се записват във Фолиото.'
    'tut_alchemy_items' = 'Предмети с <sprite name="rune_r">, <sprite name="rune_g"> или <sprite name="rune_b"> се използват за изработка на алхимични рецепти.'
    'tut_alchemy_mech' = 'Ще ти трябва и точното количество <sprite name="rune_r">, <sprite name="rune_g"> и <sprite name="rune_b"> от съставките.'
    'tut_alchemy_price' = 'За изработката на алхимични рецепти са нужни <sprite name="alchemy_flask"> и <sprite name="fire">. Ще ти трябва и точното количество <sprite name="rune_r">, <sprite name="rune_g"> и <sprite name="rune_b"> от съставките.'
    'tut_alchemy_properties' = 'Някои предмети имат алхимични свойства: <sprite name="rune_r">, <sprite name="rune_g"> и <sprite name="rune_b">.'
    'tut_alchemy_science' = 'Използвай <sprite name="science">, за да проучваш предмети на Масата за проучване. Проучването награждава с <sprite name="tech_red">, <sprite name="tech_green"> и <sprite name="tech_blue">.'
    'tut_alchemy_survey' = 'Проучването може да разкрие и алхимичните свойства на някои предмети: <sprite name="rune_r">, <sprite name="rune_g"> и <sprite name="rune_b">.'
    'tut_battle_banner' = 'За да командваш отряд, вземи и носи знамето му. Можеш да го поведеш или да го оставиш да защитава позиция.'
    'tut_battle_bars' = 'По време на битка следи лентите горе, за да знаеш кога и къде ще нападнат зомбитата.'
    'tut_battle_build' = 'За да се подготвиш за битка, построй отбранителни съоръжения близо до базата си.'
    'tut_battle_defense' = '<sprite name="barracks"> се осигуряват от отбранителни съоръжения и войските от казармите.'
    'tut_battle_flag' = 'За да превземеш знаме, победи близките врагове и задръж позицията. Колкото повече войници има край знамето, толкова по-бързо ще го превземеш.'
    'tut_battle_lose' = 'Ако враговете превземат базата ти или здравето ти свърши, губиш.'
    'tut_battle_start' = 'Започни битка, като взаимодействаш със стражевия пост.'
    'tut_battle_swords' = 'Всяка битка има изискване за <sprite name="barracks">.'
    'tut_battle_win' = 'За да спечелиш, превземи всички вражески знамена и ги задръж до края на битката.'
    'tut_commerce_day' = 'Можеш да приемаш градски поръчки само на <sprite name="day_pride">. Изпълнението им носи <sprite name="happiness"> и <sprite name="brz-m"><sprite name="slv-m"><sprite name="gld-m">.'
    'tut_commerce_delivery' = 'Достави нужните стоки в Градския склад, за да изпълниш поръчките. Там можеш да продаваш излишните стоки за пари.'
    'tut_commerce_urgent' = 'Има различни поръчки. Спешните <sprite name="icon_time"> трябва да бъдат изпълнени изцяло в рамките на една седмица.'
    'tut_craft_auto' = 'След като избереш рецепта, трябва да я изработиш. Някои работни маси изработват автоматично с течение на времето <sprite name="cell_time">, като използват гориво <sprite name="fire">.'
    'tut_craft_extensions' = 'За изработката на напреднали предмети са нужни специални приставки към работната маса.'
    'tut_craft_price' = 'За това са нужни съставки и талант.'
    'tut_craft_req' = 'За изработката са нужни съставки, <sprite name="energy"> и <sprite name="talent_orange">/<sprite name="talent_red">/<sprite name="talent_green">/<sprite name="talent_yellow">/<sprite name="talent_blue">.'
    'tut_craft_star' = 'Някои рецепти са <sprite name="icon_star">. Резултатът зависи от съставките и таланта. Колкото по-висок е талантът ти, толкова по-добро ще е качеството на изработените предмети.'
    'tut_craft_workbench' = 'Можеш да изработиш всяка позната рецепта на съответната работна маса.'
    'tut_energy_1' = "Някои действия в играта изразходват [Енергия].`r`n`r`nИзработката, събирането на ресурси и битките изискват енергия."
    'tut_energy_2' = 'Определени задачи или изтощението водят до <sprite name="insanity">. Лудостта намалява максималната ти <sprite name="energy">.'
    'tut_energy_3' = 'Винаги можеш да възстановиш енергията си с [Храна] и [Отвари]. Просто щракни с десния бутон върху тях в инвентара си.'
    'tut_energy_4' = '[Сънят] също възстановява <sprite name="energy"> и вероятно намалява <sprite name="insanity">.'
    'tut_energy_5' = '[Сънят] също възстановява <sprite name="energy">.'
    'tut_energy_consumables' = 'Някои консумативи възстановяват <sprite name="energy">.'
    'tut_energy_sleep' = 'Сънят също възстановява <sprite name="energy">.'
    'tut_energy_spend' = 'Изразходваш <sprite name="energy"> за различни действия.'
    'tut_factory_gear' = '<sprite name="gear"> определя капацитета на Фабриката ти. Задействай повече въртележки, за да го увеличиш.'
    'tut_factory_town' = 'Фабриката ти позволява напълно да автоматизираш снабдяването на града, включително производството и доставките.'
    'tut_factory_work' = 'Работните станции във Фабриката се нуждаят от зомбита, за да работят, и трябва да бъдат свързани с конвейерни ленти.'
    'tut_farming_price' = 'Засаждането струва 4 семена.'
    'tut_farming_seeds' = 'За да засадиш, вземи семената от инвентара си. Засаждането струва 4 семена.'
    'tut_farming_talent' = 'Колкото по-висок е твоят <sprite name="talent_green"> и този на лехата, толкова по-голяма ще е реколтата.'
    'tut_fishing_bait' = 'Първо избери стръв - макар че понякога можеш да ловиш и без нея. Когато кълвне, бързо натисни @(GameKeyInteraction), за да започнеш минииграта.'
    'tut_fishing_bite' = 'Когато кълвне, бързо натисни @(GameKeyInteraction), за да започнеш минииграта.'
    'tut_fishing_spots' = 'Можеш да ловиш риба на определени места.'
    'tut_fishing_talent' = 'Ако ти е трудно да ловиш риба, увеличи <sprite name="talent_green">.'
    'tut_insanity_consumables' = 'Някои консумативи могат да намалят <sprite name="insanity">.'
    'tut_insanity_energy' = '<sprite name="insanity"> намалява максималната ти <sprite name="energy">.'
    'tut_insanity_generate' = 'Някои действия създават <sprite name="insanity">. Когато си изморен, всяко действие ще създава <sprite name="insanity">.'
    'tut_insanity_spend' = 'Да спиш, когато си изморен, е най-добрият начин да намалиш <sprite name="insanity">.'
    'tut_fishing_game' = 'По време на минииграта задръж @(GameKeyInteraction), за да изтеглиш рибата. Не дърпай, когато рибата се съпротивлява, иначе кордата ще се скъса. Ако ти е трудно да ловиш риба, увеличи <sprite name="talent_green">.'
    'tut_grave_1' = 'Използвай [чертожната маса] в гробището. Маркирай място за гроб, после го изкопай с лопатата си.'
    'tut_grave_1_1' = 'Използвай чертожната маса, за да маркираш място за гроб, после го изкопай с лопатата си.'
    'tut_grave_1_2' = 'Постави трупа в гроба. Погреби го и го отбележи с надгробен кръст. По-късно ще можеш да отключиш по-добри надгробни плочи и огради.'
    'tut_grave_2' = 'Внимателно постави тялото (или каквото е останало от него) в гроба. После го погреби.'
    'tut_insp_talents_insp' = 'Извършвай различни действия, за да печелиш различни вдъхновения: <sprite name="inspiration_point-orange">, <sprite name="inspiration_point-red">, <sprite name="inspiration_point-green">, <sprite name="inspiration_point-yellow"> и <sprite name="inspiration_point-blue">.'
    'tut_insp_talents_talents' = 'Точките за вдъхновение могат да се харчат за умения и увеличаване на талантите: <sprite name="talent_orange">, <sprite name="talent_red">, <sprite name="talent_green">, <sprite name="talent_yellow"> и <sprite name="talent_blue">.'
    'tut_modules_info' = 'Изграждането на гробището използва модули.'
    'tut_modules_limited' = 'Броят на модулите е ограничен.'
    'tut_modules_place' = 'Първо постави модул, после го надстрой.'
    'tut_pr_machine_cap' = 'Има ограничение за броя зомбита, които можеш да имаш. За да създадеш още зомбита, използвай Машината за намаляване на паниката.'
    'tut_pr_machine_charge' = 'Поставяй вестници и заредени хипнотични устройства в Машината за намаляване на паниката всеки <sprite name="day_gluttony">, за да увеличиш ограничението за седмицата.'
    'tut_pr_machine_debuff' = 'Превишаването на ограничението за зомбита ще ти даде отрицателен ефект, докато не се вместиш в ограничението.'
    'tut_resurrection_day' = 'Тук можеш да възкресяваш зомбита всеки <sprite name="day_envy">. Подготви всичко предварително.'
    'tut_resurrection_device' = 'По време на <sprite name="day_envy"> стаята е захранена. Използвай Устройството за възкресение, за да върнеш зомбитата към живот.'
    'tut_resurrection_power' = 'Постави труп с Течност за реанимация, <sprite name="faith"> и нашийник за зомби на масата.'
    'tut_resurrection_room' = 'Тук можеш да възкресяваш трупове. При зомбитата повече <sprite name="rskull"> е по-добре.'
    'tut_resurrection_skulls' = 'При зомбитата повече <sprite name="rskull"> и по-малко <sprite name="skull"> е по-добре.'
    'tut_sermons_chance' = 'Шанс за успех: 67%'
    'tut_sermons_day' = 'Всеки <sprite name="day_wrath"> можеш да изнесеш проповед в църквата.'
    'tut_sermons_likes' = 'Печели <sprite name="happiness">, като изпълняваш задачи и поръчки. Колкото по-добра е церемонията, толкова повече <sprite name="happiness_cross"> са нужни за успех.'
    'tut_sermons_parishioners' = 'Проповедите изразходват <sprite name="happiness"> и изискват <sprite name="cross">. По-ниската от двете стойности - <sprite name="happiness_cross"> - определя колко миряни ще присъстват.'
    'tut_sermons_reward' = 'Колкото по-добра е церемонията, толкова повече <sprite name="happiness_cross"> са нужни за успех.'
    'tut_squad_emblem' = 'Получи емблема на защитник!'
    'tut_squad_equipment' = 'Зомбитата се бият само ако са екипирани с броня и пика или лък.'
    'tut_squad_form' = 'За да сформираш отряд, заведи зомбита в казармата и ги постави в слот за отряд.'
    'tut_squad_hdr' = 'Урок: Отряди от зомбита'
    'tut_squad_mercenaries' = 'В бъдещите битки можеш да използваш собствените си отряди от зомбита и да продължиш да наемаш наемници.'
    'tut_squad_multiple' = 'С напредването на историята ще можеш да използваш повече отряди в една битка.'
    'tut_squad_own' = 'Вече можеш да сформираш собствени отряди от зомбита.'
    'tut_squad_unlock' = 'За да отключиш слот за отряд, говори с Бойния овен в казармата.'
    'tut_survey_hdr' = 'Урок: Проучване'
    'tut_survey_runes' = 'Руни:'
    'tut_survey_science' = 'Получавай <sprite name="science">, като разграждаш специални предмети на Масата за проучване.'
    'tut_tech_1' = 'За да изработваш нови предмети, трябва да отключиш съответната технология. Това струва технологични точки. (Натисни @(GameKeyCharacterWindow), за да отвориш дървото на технологиите.)'
    'tut_tech_2' = 'Червените точки представят уменията ти за ръчна изработка и способността ти да работиш с материали.'
    'tut_skulls_1' = 'Човешките останки имат свои уникални духовни свойства. Трупът получава своите <sprite name="rskull"><sprite name="skull"> от частите на тялото си. Можеш да промениш <sprite name="rskull"><sprite name="skull"> на трупа, като отстраняваш органи и балсамираш.'
    'tut_skulls_2' = 'Основният начин да увеличиш <sprite name="wskull"> на гробището си е да украсяваш гробовете с предмети, които имат повече <sprite name="wr">.'
    'tut_skulls_3' = 'Редовете, които имат едновременно <sprite name="skull"> и <sprite name="wr">, се броят за един <sprite name="wskull">. Редовете с <sprite name="rskull"> никога не се броят, но трябва да ги запълниш с <sprite name="wr">, за да достигнеш редовете с <sprite name="skull">.'
    'tut_squad_quality' = 'Колкото по-добро е оборудването на зомбитата ти, толкова по-висок е <sprite name="barracks">.'
    'tut_tech_3' = 'Зелените точки представят познанията ти за природата и самата природа.'
    'tut_tech_4' = 'Сините точки представят духовните ти познания за нематериалния свят. Ще получиш първите си <sprite name="tech_blue"> на [Масата за проучване] в мазето на църквата.'
    'tut_tech_5' = 'Печелиш точки просто като вършиш разни неща. Можеш да печелиш точки и като изучаваш нови предмети на тази специална маса.'
    'tut_tech_hdr' = 'Урок: Технологии'
    'tut_tech_hidden' = 'Някои умения са скрити или изискват определена репутация с друг персонаж.'
    'tut_tech_price' = 'Това струва <sprite name="tech_red">, <sprite name="tech_green"> и <sprite name="tech_blue">.'
    'tut_tech_unlock' = 'Отключвай нови технологии в дървото на технологиите. Това струва <sprite name="tech_red">, <sprite name="tech_green"> и <sprite name="tech_blue">.'
    'tut_town_building' = 'Възстановените части на града могат да бъдат обновени чрез строеж на къщи и магазини.'
    'tut_town_hdr' = 'Урок: Строителство'
    'tut_town_houses' = 'Къщите дават зелени свитъци. Доставяй ги на Линда всеки <sprite name="day_lust">, за да увеличиш <sprite name="reputation-citizens"> и максималната си граница на <sprite name="happiness">.'
    'tut_town_shops' = 'Магазините отключват нови търговци и градски поръчки, като същевременно увеличават <sprite name="village_REP">. Градските поръчки са основният източник на <sprite name="happiness">.'
    'tut_trading_change' = 'Цените са динамични: колкото повече има търговецът, толкова по-ниски са цените.'
    'tut_trading_hdr' = 'Урок: Търговия'
    'tut_trading_likes' = 'Можеш да печелиш <sprite name="happiness"> и като търгуваш с определени специални стоки.'
    'tut_trading_money' = 'Търговията ти дава достъп до различни предмети и е чудесен начин да печелиш <sprite name="brz-m">, <sprite name="slv-m"> и <sprite name="gld-m">.'
    'tut_trading_restock' = 'Стоките на търговеца се обновяват с времето. Можеш също да подобриш търговеца, за да разшириш инвентара му.'
    'tut_trading_special' = 'Всеки търговец има свои стоки за купуване и продаване, като някои са специални само за него.'
    'tut_zombie_work_hdr' = 'Урок: Работници зомбита'
    'tut_zombie_work_supply' = 'Зомбитата снабдители доставят нужните предмети на зомбитата на работните станции и зареждат предмети на работните маси за автоматична изработка.'
    'tut_zombie_work_talents' = 'Работниците зомбита имат свои нива на талант <sprite name="talent_orange">, <sprite name="talent_red">, <sprite name="talent_green">, <sprite name="talent_yellow">, <sprite name="talent_blue"> и умения, които също могат да се подобряват. Могат да използват и оборудване.'
    'tut_zombie_work_work' = 'Поставяй работници зомбита на работните станции, за да им възлагаш различни задачи и изработка.'
    'tut_zone_quality_different' = 'Различните места могат да имат собствено качество.'
    'tut_zone_quality_hdr' = 'Урок: Качество на зоните'
    'tut_zone_quality_icons' = 'Например гробището използва <sprite name="wr">.'
    'tut_zone_quality_improve' = 'Строй, ремонтирай и почиствай, за да подобриш качеството.'
}

$rows = @(Import-Csv -LiteralPath $path)
foreach ($row in $rows) {
    if ($translations.ContainsKey($row.key)) {
        $row.bg = $translations[$row.key]
        $row.status = 'translated'
        $row.notes = 'Short hint/tutorial heading pilot translation.'
    }
}
$reviewKeys = @('hint_build')
foreach ($row in $rows) {
    if ($reviewKeys -contains $row.key) {
        $row.status = 'review'
        $row.notes = 'Check the command wording in the in-game build context.'
    }
}
$rows | ConvertTo-Csv -NoTypeInformation | Set-Content -LiteralPath $path -Encoding utf8
Write-Output "Seeded $($translations.Count) short hints and tutorial headings."
